# Generated by Django 3.2 on 2022-09-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, default='Anonymous User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
