# Generated by Django 3.2 on 2022-08-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='use_as_testinomial',
            new_name='use_as_testimonial',
        ),
    ]
