# Generated by Django 3.2 on 2022-08-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_use_as_testinomial_song_use_as_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.genre', verbose_name='Instruments'),
        ),
        migrations.AlterField(
            model_name='song',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='song_instrument', to='songs.Instrument', verbose_name='Instruments'),
        ),
    ]
