# Generated by Django 3.2 on 2022-08-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20220805_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, default='media/placeholder.jpg', null=True, upload_to=''),
        ),
    ]
