# Generated by Django 3.2 on 2022-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
    ]
