# Generated by Django 3.2 on 2022-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_of_reviews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
