# Generated by Django 3.2 on 2022-08-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_alter_song_num_of_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ong_instruments', to='songs.song')),
            ],
        ),
    ]
