# Generated by Django 3.2 on 2022-08-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_remove_song_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstrument',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_instruments', to='songs.song'),
        ),
    ]
