# Generated by Django 3.2 on 2022-08-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_alter_songinstrument_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinstrument',
            name='name',
        ),
        migrations.AddField(
            model_name='songinstrument',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_song', to='songs.instrument'),
        ),
    ]
