# Generated by Django 3.2 on 2022-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_auto_20220821_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinstrument',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
