# Generated by Django 3.2 on 2022-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0021_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
