# Generated by Django 3.2 on 2022-08-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0022_alter_song_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstrument',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_song', to='songs.instrument'),
        ),
    ]
