# Generated by Django 3.2 on 2022-09-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0023_alter_songinstrument_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video_file',
        ),
    ]
